import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import { Toaster } from 'sonner'
import { cookies } from 'next/headers'
import './globals.css'
import { cn } from '@/lib/utils'
import { TRPCReactProvider } from '@/trpc/react'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					GeistSans.className
				)}
			>
				<TRPCReactProvider cookies={cookies().toString()}>
					{children}
					<Toaster closeButton={true} position='top-center' />
				</TRPCReactProvider>
			</body>
		</html>
	)
}
